name: Deploy MkDocs

on:
  workflow_dispatch:
    inputs:
      confirm_deployment:
        description: 'Type "deploy" to confirm deployment'
        required: true
        default: ''

jobs:
  deploy_mkdocs:
    if: inputs.confirm_deployment == 'deploy'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      
      - name: Cache MkDocs dependencies
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ github.run_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
              
      - name: Install MkDocs and dependencies
        run: |
          uv pip install --system mkdocs-material python-dotenv mkdocs-macros-plugin mkdocs-glightbox
          
      - name: Deploy MkDocs to GitHub Pages
        run: mkdocs gh-deploy --force
        
      - name: Summary
        run: |
          echo "✅ Successfully deployed documentation"
          echo "📖 Documentation: https://$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]').github.io/$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')/"