name: Deploy to Docker Hub

on:
  workflow_dispatch:
    inputs:
      confirm_deployment:
        description: 'Type "deploy" to confirm deployment'
        required: true
        default: ''
  workflow_call:
    inputs:
      confirm_deployment:
        description: 'Type "deploy" to confirm deployment'
        type: string
        required: true

jobs:
  setup:
    uses: ./.github/workflows/deploy-setup.yml
    with:
      confirm_deployment: ${{ inputs.confirm_deployment }}
    secrets: inherit

  deploy_to_docker:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and tag Docker image
        run: |
          echo "Building: ${{ secrets.DOCKER_USERNAME }}/${{ needs.setup.outputs.project_name }}:${{ needs.setup.outputs.version }}"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ needs.setup.outputs.project_name }}:${{ needs.setup.outputs.version }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ needs.setup.outputs.project_name }}:${{ needs.setup.outputs.version }} ${{ secrets.DOCKER_USERNAME }}/${{ needs.setup.outputs.project_name }}:latest
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ needs.setup.outputs.project_name }}:${{ needs.setup.outputs.version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ needs.setup.outputs.project_name }}:latest
          
  docker_summary:
    needs: [setup, deploy_to_docker]
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: |
          echo "Successfully deployed ${{ needs.setup.outputs.project_name }} to Docker Hub for version ${{ needs.setup.outputs.version }}"
          echo "- Docker Hub: ${{ secrets.DOCKER_USERNAME }}/${{ needs.setup.outputs.project_name }}:${{ needs.setup.outputs.version }}"